# Thanks to https://github.com/Mrs4s/go-cqhttp/blob/master/.github/workflows/ci.yml

name: CI

on: 
  push:
    branches: [master]

env:
  BINARY_PREFIX: ""
  BINARY_SUFFIX: ""

jobs:

  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm, arm64]
        exclude:
          - goos: darwin
            goarch: arm
          - goos: darwin
            goarch: "386"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      
      - name: Build binary file
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          if [ $GOOS = "windows" ]; then export BINARY_SUFFIX="$BINARY_SUFFIX.exe"; fi
          go build -o "output/$BINARY_PREFIXclient_$GOOS_$GOARCH$BINARY_SUFFIX" -trimpath ./client
          go build -o "output/$BINARY_PREFIXserver_$GOOS_$GOARCH$BINARY_SUFFIX" -trimpath ./server
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: wg-nat_${{ matrix.goos }}_${{ matrix.goarch }}
          path: output/